DROP FUNCTION IF EXISTS AUTH_CONNECT_BY_PARENT;
CREATE FUNCTION `AUTH_CONNECT_BY_PARENT`() RETURNS int(11)
    READS SQL DATA
BEGIN
  DECLARE _ID INT;
  DECLARE _PARENT INT;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET @ID = NULL;

  SET _PARENT = @ID;
  SET _ID = -1;

  IF @ID IS NULL THEN
    RETURN NULL;
  END IF;

  LOOP
    SELECT MIN(AUTH_NO)
      INTO @ID
      FROM AUTH
     WHERE UP_AUTH_NO = _PARENT
       AND AUTH_NO > _ID;

    IF @ID IS NOT NULL OR _PARENT = @START_WITH THEN
      SET @LEVEL = @LEVEL + 1;
      RETURN @ID;
    END IF;

    SET @LEVEL := @LEVEL - 1;

    SELECT AUTH_NO, UP_AUTH_NO
      INTO _ID, _PARENT
      FROM AUTH
     WHERE AUTH_NO = _PARENT;
  END LOOP;
END;
