DROP FUNCTION IF EXISTS CORP_CONNECT_BY_PARENT;
CREATE FUNCTION `CORP_CONNECT_BY_PARENT`() RETURNS int(11)
    READS SQL DATA
BEGIN
  DECLARE _ID INT;
  DECLARE _PARENT INT;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET @ID = NULL;

  SET _PARENT = @ID;
  SET _ID = -1;

  IF @ID IS NULL THEN
    RETURN NULL;
  END IF;

  LOOP
    SELECT MIN(CORP_ID)
      INTO @ID
      FROM CORP_INFO
     WHERE UP_CORP_ID = _PARENT
       AND CORP_ID > _ID;

    IF @ID IS NOT NULL OR _PARENT = @START_WITH THEN
      SET @LEVEL = @LEVEL + 1;
      RETURN @ID;
    END IF;

    SET @LEVEL := @LEVEL - 1;

    SELECT CORP_ID, UP_CORP_ID
      INTO _ID, _PARENT
      FROM CORP_INFO
     WHERE CORP_ID = _PARENT;
  END LOOP;
END;
