CREATE TABLE `CRAWL_BOARD_PART` (
  `PART` int(10) NOT NULL COMMENT '수집구분',
  `TITLE` varchar(500) DEFAULT NULL COMMENT '수집제목',
  `CRAWL_URL` varchar(500) DEFAULT NULL COMMENT '수집주소',
  `CRAWL_PART` varchar(20) DEFAULT NULL COMMENT '수집메소드',
  `CRAWL_YN` char(1) DEFAULT NULL COMMENT '수집여부',
  `USE_YN` char(1) DEFAULT NULL COMMENT '게시판사용여부',
  PRIMARY KEY (`PART`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='수집게시판분류';

CREATE TABLE `CRAWL_BOARD_TMP` (
  `PART` int(10) NOT NULL COMMENT '수집구분',
  `SEQ` int(10) NOT NULL COMMENT '순번',
  `LINK` varchar(500) DEFAULT NULL COMMENT '본문링크',
  `SUBJECT` varchar(500) DEFAULT NULL COMMENT '링크제목',
  `CONTENT` longtext COMMENT '본문내용',
  `PUBDATE` varchar(20) DEFAULT NULL COMMENT '게시날짜',
  `CONT_YN` char(1) DEFAULT NULL COMMENT '내용수집여부',
  `IMG_YN` char(1) DEFAULT NULL COMMENT '이미지수집여부',
  `COMMIT_YN` char(1) DEFAULT NULL COMMENT '서비스이관여부',
  `REG_DT` datetime NOT NULL COMMENT '등록일',
  PRIMARY KEY (`PART`,`SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='수집게시판템프테이블';


CREATE TABLE `CRAWL_BOARD` (
  `PART` int(10) NOT NULL COMMENT '구분',
  `SEQ` int(10) NOT NULL COMMENT '순번',
  `SUBJECT` varchar(500) DEFAULT NULL COMMENT '제목',
  `LINK` varchar(500) DEFAULT NULL COMMENT '원본링크',
  `CONTENT` mediumtext COMMENT '내용',
  `PUBDATE` varchar(20) DEFAULT NULL COMMENT '게시일',
  `REG_DT` datetime NOT NULL COMMENT '등록일',
  PRIMARY KEY (`PART`,`SEQ`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='서비스게시판';




CREATE TABLE `AUTH` (
  `AUTH_ID` VARCHAR(50) NOT NULL COMMENT '권한코드',
  `AUTH_NM` VARCHAR(200) DEFAULT NULL COMMENT '권한명',
  `AUTH_NO` INT(4) DEFAULT NULL COMMENT '권한번호',
  `UP_AUTH_NO` INT(4) DEFAULT NULL COMMENT '상위권한번호',
  PRIMARY KEY (`AUTH_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='권한정보';

CREATE TABLE `AUTH_LVL` (
  `PARENT_AUTH_ID` VARCHAR(50) NOT NULL COMMENT '부모권한코드',
  `CHILD_AUTH_ID` VARCHAR(50) NOT NULL COMMENT '자식권한코드',
  PRIMARY KEY (`PARENT_AUTH_ID`,`CHILD_AUTH_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='권한레벨';

CREATE TABLE `CODE_PART` (
  `CODE_PART` VARCHAR(20) NOT NULL COMMENT '코드그룹',
  `CODE_PART_NM` VARCHAR(30) NOT NULL COMMENT '코드그룹명',
  `MOD_DT` DATETIME NOT NULL COMMENT '수정일',
  `MOD_ID` VARCHAR(20) NOT NULL COMMENT '수정자아이디',
  `MOD_IP` VARCHAR(80) NOT NULL COMMENT '수정자아이피',
  `REG_DT` DATETIME NOT NULL COMMENT '등록일',
  `REG_ID` VARCHAR(20) NOT NULL COMMENT '등록자아이디',
  `REG_IP` VARCHAR(80) NOT NULL COMMENT '등록자아이피',
  PRIMARY KEY (`CODE_PART`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='코드그룹';

CREATE TABLE `CODE_INFO` (
  `CODE_PART` VARCHAR(20) NOT NULL COMMENT '코드그룹',
  `CODE` VARCHAR(20) NOT NULL COMMENT '코드',
  `CODE_NM` VARCHAR(200) NOT NULL COMMENT '코드명',
  `CODE_ORD` VARCHAR(5) DEFAULT NULL COMMENT '코드정렬순서',
  `CODE_DESC` VARCHAR(500) DEFAULT NULL COMMENT '코드설명',
  `MOD_DT` DATETIME NOT NULL COMMENT '수정일',
  `MOD_ID` VARCHAR(20) NOT NULL COMMENT '수정자아이디',
  `MOD_IP` VARCHAR(80) NOT NULL COMMENT '수정자아이피',
  `REG_DT` DATETIME NOT NULL COMMENT '등록일',
  `REG_ID` VARCHAR(20) NOT NULL COMMENT '등록자아이디',
  `REG_IP` VARCHAR(80) NOT NULL COMMENT '등록자아이피',
  PRIMARY KEY (`CODE_PART`,`CODE`),
  CONSTRAINT `FK_CODE_PART_TO_CODE_INFO` FOREIGN KEY (`CODE_PART`) REFERENCES `CODE_PART` (`CODE_PART`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='공통코드';



CREATE TABLE `CRAWL_BOARD_PART` (
  `PART` INT(10) NOT NULL COMMENT '수집구분',
  `TITLE` VARCHAR(500) DEFAULT NULL COMMENT '수집제목',
  `CRAWL_URL` VARCHAR(500) DEFAULT NULL COMMENT '수집주소',
  `CRAWL_PART` VARCHAR(20) DEFAULT NULL COMMENT '수집메소드',
  `CRAWL_YN` CHAR(1) DEFAULT NULL COMMENT '수집여부',
  `USE_YN` CHAR(1) DEFAULT NULL COMMENT '게시판사용여부',
  PRIMARY KEY (`PART`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='수집게시판분류';

CREATE TABLE `CRAWL_BOARD_TMP` (
  `PART` INT(10) NOT NULL COMMENT '수집구분',
  `SEQ` INT(10) NOT NULL COMMENT '순번',
  `LINK` VARCHAR(500) DEFAULT NULL COMMENT '본문링크',
  `SUBJECT` VARCHAR(500) DEFAULT NULL COMMENT '링크제목',
  `CONTENT` LONGTEXT COMMENT '본문내용',
  `READ_CNT` INT(11) DEFAULT NULL COMMENT '읽은수',
  `PUBDATE` VARCHAR(20) DEFAULT NULL COMMENT '게시날짜',
  `CONT_YN` CHAR(1) DEFAULT NULL COMMENT '내용수집여부',
  `IMG_YN` CHAR(1) DEFAULT NULL COMMENT '이미지수집여부',
  `COMMIT_YN` CHAR(1) DEFAULT NULL COMMENT '서비스이관여부',
  `REG_DT` DATETIME NOT NULL COMMENT '등록일',
  PRIMARY KEY (`PART`,`SEQ`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='수집게시판템프테이블';

CREATE TABLE `CRAWL_STATUS` (
  `CRAWLING_YN` CHAR(1) DEFAULT NULL COMMENT '수집실행여부',
  `MOD_DT` DATETIME NOT NULL COMMENT '수정일'
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='수집게시판분류';

CREATE TABLE `MENU_AUTH` (
  `MENU_ID` INT(10) UNSIGNED NOT NULL COMMENT '메뉴아이디',
  `AUTH_ID` VARCHAR(50) NOT NULL COMMENT '권한코드',
  PRIMARY KEY (`MENU_ID`,`AUTH_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='메뉴-권한';

CREATE TABLE `MENU_INFO` (
  `MENU_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '메뉴아이디',
  `MENU_NM` VARCHAR(50) NOT NULL COMMENT '메뉴명',
  `MENU_URL` VARCHAR(50) DEFAULT NULL COMMENT '링크주소',
  `UP_MENU_ID` INT(10) UNSIGNED DEFAULT '0' COMMENT '상위메뉴아이디',
  `MOD_DT` DATETIME NOT NULL COMMENT '수정일',
  `MOD_ID` VARCHAR(20) NOT NULL COMMENT '수정자아이디',
  `MOD_IP` VARCHAR(80) NOT NULL COMMENT '수정자아이피',
  `REG_DT` DATETIME NOT NULL COMMENT '등록일',
  `REG_ID` VARCHAR(20) NOT NULL COMMENT '등록자아이디',
  `REG_IP` VARCHAR(80) NOT NULL COMMENT '등록자아이피',
  PRIMARY KEY (`MENU_ID`)
) ENGINE=INNODB AUTO_INCREMENT=18 DEFAULT CHARSET=UTF8 COMMENT='메뉴정보';

CREATE TABLE `NEWS_LST` (
  `PROVIDE_CD` VARCHAR(20) NOT NULL COMMENT '뉴스제공사',
  `NEWS_TIME` VARCHAR(15) NOT NULL COMMENT '뉴스수집시간',
  `SEQ` INT(3) DEFAULT NULL COMMENT '순번',
  `SUBJECT` VARCHAR(500) DEFAULT NULL COMMENT '뉴스제목',
  `LINK` VARCHAR(500) DEFAULT NULL COMMENT '뉴스링크',
  `CATEGORY` VARCHAR(5) DEFAULT NULL COMMENT '뉴스분류',
  `PUBDATE` VARCHAR(50) DEFAULT NULL COMMENT '발표시간'
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='뉴스목록';

CREATE TABLE `RESO_AUTH` (
  `RESO_ID` VARCHAR(50) NOT NULL COMMENT '리소스아이디',
  `AUTH_ID` VARCHAR(50) NOT NULL COMMENT '권한코드',
  `AUTH_NM` VARCHAR(200) DEFAULT NULL COMMENT '권한명',
  PRIMARY KEY (`RESO_ID`,`AUTH_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='리소스-권한';

CREATE TABLE `RESO_INFO` (
  `RESO_ID` VARCHAR(50) NOT NULL COMMENT '리소스아이디',
  `RESO_NM` VARCHAR(200) DEFAULT NULL COMMENT '리소스명',
  `RESO_PTN` VARCHAR(200) DEFAULT NULL COMMENT '리소스패턴',
  `RESO_TP` VARCHAR(10) DEFAULT NULL COMMENT '리소스타입',
  `RESO_ORD` INT(3) DEFAULT NULL COMMENT '순서',
  PRIMARY KEY (`RESO_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='리소스 정보';

CREATE TABLE `USER_AUTH` (
  `USER_ID` VARCHAR(20) NOT NULL COMMENT '사용자아이디',
  `AUTH_ID` VARCHAR(50) NOT NULL COMMENT '권한코드',
  PRIMARY KEY (`USER_ID`,`AUTH_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='사용자-권한';

CREATE TABLE `USER_INFO` (
  `USER_ID` VARCHAR(20) NOT NULL COMMENT '사용자아이디',
  `USER_NM` VARCHAR(50) NOT NULL COMMENT '이름',
  `USER_PW` VARCHAR(50) NOT NULL COMMENT '패스워드',
  `USER_EMAIL` VARCHAR(50) DEFAULT NULL COMMENT '이메일',
  `USER_HP` VARCHAR(15) DEFAULT NULL COMMENT '휴대전화번호',
  `USER_TEL` VARCHAR(15) DEFAULT NULL COMMENT '일반전화번호',
  `USER_AUTH` CHAR(1) NOT NULL COMMENT '회원등급',
  `USE_YN` CHAR(1) NOT NULL COMMENT '사용여부',
  `ACCESS_FAIL_CNT` INT(2) DEFAULT NULL COMMENT '로그인실패횟수',
  `MOD_DT` DATETIME NOT NULL COMMENT '수정일',
  `MOD_ID` VARCHAR(20) NOT NULL COMMENT '수정자아이디',
  `MOD_IP` VARCHAR(80) NOT NULL COMMENT '수정자아이피',
  `REG_DT` DATETIME NOT NULL COMMENT '등록일',
  `REG_ID` VARCHAR(20) NOT NULL COMMENT '등록자아이디',
  `REG_IP` VARCHAR(80) NOT NULL COMMENT '등록자아이피',
  PRIMARY KEY (`USER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='사용자';

